### PR TITLE
rc3: all requirements implemented

### PR DESCRIPTION
**Pull request by sorenvind**
So. A very minimalistic web frontend has been implemented, which retrieves and posts data to the previously implemented REST service. Demo video in demo.mov.

Jetty serves up static files. 
AngularJS ngResource used for AJAX calls implemented in controller.
Successful addition of new message reloads recent list.
Moved REST service from java package "app" to package "rest".

### CODE REVIEW

**Comment by sorenvind** [comment]
Oh, and tagging you two: @callebjorkell @mortenholm

**Comment by callebjorkell** [comment]
If you need to put a comma in the commit message, it's a sign that you should have two commits :wink:

**Comment by callebjorkell** [comment]
But looks very good! Will merge. Congrats etc etc :smile:

**Comment by callebjorkell** [comment]
Oh, and for future reference, you don't of course want to add videos to the git repo. For this specific case however, it's fine. Generally speaking you want box, yammer or other file service for that stuff.

**Pull request merged**
