### PR TITLE
code challenge second iteration

### PR DESCRIPTION
**Pull request by jennifergao86**
@callebjorkell

### CODE REVIEW

**Comment by callebjorkell** [comment]
You're missing parts the following requirements:
* *The database schema is initialized during the bootup of the project*. The database and user can be created manually.
* The project build runs JUnit tests using Mockito for mock objects producing over *60% line coverage measured using Jacoco*.

I would also love to see a screenshot of the test report on the PR.

**Comment by jennifergao86** [comment]
Do you mean the sql sentence to create the table I'm accessing to? for the database part?And a coverage screenshot for the second one?

**Comment by jennifergao86** [comment]
I used jacoco built in Intellij. Is that OK?

**Comment by callebjorkell** [comment]
SQL - if/when the database is empty when you start the service, the schema should be automatically initialized.

Coverage - Hook up jacoco to the build (maven) and show the jacoco test report somehow. The intention was to verify that the coverage is OK by failing the build if line coverage is below 60%, but that was sort of left out of the specs it seems.

**Pull request closed without merging**
