### PR TITLE
Final iteration

### PR DESCRIPTION
**Pull request by atefeh-kh**
@callebjorkell request pull for final iteration

### CODE REVIEW

**Comment by callebjorkell** [comment]
Please include a demo video somewhere, as per the requirements.

**Comment by atefeh-kh** [comment]
I guess I've already included it- Demo.mov, am I mistaken?


On Tue, Apr 28, 2015 at 3:50 PM, Carl-Magnus Björkell <
notifications@github.com> wrote:

> Please include a demo video somewhere, as per the requirements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/callebjorkell/codechallenge-batman/pull/18#issuecomment-97070608>
> .
>



-- 
Kind regards,

Atefeh Khosravi
Developer Copenhagen

Cell: +45 91975951
Skype: ati_khosravi

TRADESHIFT
Amazing things happen when businesses connect.
tradeshift.com ׀ tradeshift blog <http://blog.tradeshift.com/>

**Comment by callebjorkell** [comment]
Selective blindness.

**Comment by callebjorkell** [comment]
:ribbon:

**Pull request merged**
